seed: 123456
step_size: 0.04
max_iterations: 12000
max_sampling: 6000
distance_metric_weights: [3.0, 2.0, 2.0, 1.5, 1.5, 1.0, 1.0]
task_space_frame_name: tcp_L_Link
task_space_limits: [[-1.0, 1.0], [-1.0, 1.0], [-0.8, 1.0]]
c_space_planning_params:
  exploration_fraction: 0.5
task_space_planning_params:
  translation_target_zone_tolerance: 0.04
  orientation_target_zone_tolerance: 0.09
  translation_target_final_tolerance: 0.002
  orientation_target_final_tolerance: 0.01
  translation_gradient_weight: 1.0
  orientation_gradient_weight: 0.125
  nn_translation_distance_weight: 1.0
  nn_orientation_distance_weight: 0.125
  task_space_exploitation_fraction: 0.4
  task_space_exploration_fraction: 0.1
  max_extension_substeps_away_from_target: 6
  max_extension_substeps_near_target: 50
  extension_substep_target_region_scale_factor: 2.0
  unexploited_nodes_culling_scalar: 1.0
  gradient_substep_size: 0.025
